server:
  port: 8080
spring:
  application:
    name: soccer-server
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/auth
    #    username: postgres
    #    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:auth
    username: sa
    password: 111111
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
          max-age: 86400
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) [%12.12t] %clr(%-50.50logger{49}){cyan} [%5.5L] : %m%n%wEx'
  level:
    root: info
    com.dqv5: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

soccer:
  system:
    log: true
  roles:
    - roleValue: ROLE_NORMAL
      roleName: 普通用户
    - roleValue: ROLE_ADMIN
      roleName: 超级管理员
  users:
    - username: admin
      password: 123456
      nickName: 管理员
      role: ROLE_ADMIN
    - username: tom
      password: 111111
      nickName: 汤姆
      role: ROLE_NORMAL
    - username: jerry
      password: 222222
      nickName: 杰瑞
      role: ROLE_NORMAL
    - username: blank
      password: 333333
      nickName: 白板
