server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/soccer
    username: postgres
    password: 123456
logging:
  level:
    root: info
    com.dqv5: debug
