server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: soccer-server
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:soccer
    username: sa
    password: 111111
  liquibase:
    enabled: true
    change-log: classpath:liquibase/common/db.changelog-master.xml
    database-change-log-table: LIQUIBASE_CHANGELOG
    database-change-log-lock-table: LIQUIBASE_CHANGELOG_LOCK
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
          max-age: 86400
mybatis-plus:
  mapper-locations: classpath:/mapper/sqlMap/*.xml
  config-location: classpath:/mapper/mybatis-config.xml
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) [%12.12t] %clr(%-50.50logger{49}){cyan} [%5.5L] : %m%n%wEx'
  level:
    root: info
    com.dqv5: debug

soccer:
  system:
    log: true
  roles:
    - roleValue: ROLE_NORMAL
      roleName: 普通用户
    - roleValue: ROLE_ADMIN
      roleName: 超级管理员
  users:
    - username: admin
      password: 123456
      nickName: 管理员
      role: ROLE_ADMIN
    - username: tom
      password: 111111
      nickName: 汤姆
      role: ROLE_NORMAL
    - username: jerry
      password: 222222
      nickName: 杰瑞
      role: ROLE_NORMAL
    - username: blank
      password: 333333
      nickName: 白板
