server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/E:\workspace_personal\spring-boot-angular\1.data\soccer
    username: sa
    password: 111111
logging:
  level:
    root: info
    com.dqv5: debug
