server:
  port: 8080
spring:
  datasource:
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/auth
    #    username: postgres
    #    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:auth
    username: sa
    password: 111111
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
logging:
  file:
    path: logs
  logback:
    rollingpolicy:
      max-history: 365
      max-file-size: 50MB
  level:
    root: info
    com.dqv5: info
    org.hibernate.SQL: error
    org.hibernate.type.descriptor.sql.BasicBinder: error
